
create table SinhVien
(
ID INT  PRIMARY KEY NOT NULL,
HOSV NVARCHAR(50) NOT NULL,
TENSV NVARCHAR(10) NOT NULL,
LOP VARCHAR (10),
DIEMTB INT,
 
)
INSERT INTO SinhVien(ID,HOSV,TENSV,LOP,DIEMTB)
VALUES 
(1,N'Nguyễn Văn',N'AN','12A ',8.5),
(2,N'Trần Thị',N'Bình','11B',9.0),
(3,N'Lê Văn',N'Cường','12A',7.2),
(4,N'Phạm Thị',N'Dung','10C',9.5),
(5,N'Hoàng Văn',N'Em','11B',8.0),
(6,N'Nguyễn Văn',N'Em','11B',6.0)


SELECT * FROM SinhVien
 

 SELECT COUNT(*) AS TONGHOCSINH FROM SinhVien

 SELECT CONCAT(TENSV, '(',LOP,')') AS THONGTIN FROM SinhVien /* CONCAT NỐI CHUỖI */


 CREATE TABLE NHANVIEN
 (
 ID INT NOT NULL PRIMARY KEY,
 HO NVARCHAR (30)NOT NULL,
 TEN NVARCHAR (10)NOT NULL,
 PHONGBAN VARCHAR(25) NOT NULL,
 LUONG INT ,
 NGAYGIANHAP DATE NOT NULL,
 )

 INSERT INTO NHANVIEN(ID, HO, TEN, PHONGBAN, LUONG ,NGAYGIANHAP)
 VALUES
(2,N'Trần Thị',N'Bình',N'Kế toán',55000,'2019-03-01'),
(3,N'Lê Văn',N'Cường',N'IT',75000,'2021-07-30'),
(4,N'Phạm Thị',N'Dung',N'Nhân sự',50000,'2022-02-11'),
(5,N'Hoàng Văn ',N'Em',N'Kế toán',58000,'2020-11-20'),
(6,N'Bùi Minh ',N'Tuấn',N'Giám đốc',120000,'2018-05-01'),
(7,N'Võ Thị ',N'Lan',N'IT',NULL,'2023-01-05')


SELECT CONCAT(HO,' ',TEN,'') AS HOVATEN , LUONG AS THUNHAP  FROM NHANVIEN


SELECT 
	HO,
	TEN ,
	LUONG,
	CASE 
		WHEN LUONG > 100000 THEN N'CAO VCL'
		WHEN LUONG > 60000 THEN N'Cao'
		ELSE N'TRUNGBINH'
	END AS XEPLOAILUONG
FROM NHANVIEN								 /* MỆNH ĐỀ IF ELSE */

SELECT * FROM NHANVIEN WHERE PHONGBAN = N'IT' AND LUONG > 70000
SELECT * FROM NHANVIEN WHERE PHONGBAN = N'IT' OR PHONGBAN = N'K? toán';/* // */ SELECT * FROM NHANVIEN WHERE PHONGBAN IN ( N'IT',N'K? toán',N'Nhân s?');

SELECT * FROM NHANVIEN WHERE LUONG BETWEEN 50000 AND 60000;

SELECT * FROM NHANVIEN WHERE LUONG IS NULL
